# Generated by Django 4.0.3 on 2022-04-07 06:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='reviews',
        ),
        migrations.AddField(
            model_name='review',
            name='show',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.show'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='date_written',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='show',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
